// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByrYl-HEWdr9k0bzZ3bc8_yinF4ETDYfo',
    appId: '1:198087606683:web:c7b9fb57e8b1bbf24ea13e',
    messagingSenderId: '198087606683',
    projectId: 'curso-flutter-cd410',
    authDomain: 'curso-flutter-cd410.firebaseapp.com',
    storageBucket: 'curso-flutter-cd410.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2u-usSN6cMWEonzprxch4VuDVgJLpJA',
    appId: '1:198087606683:android:dc7ac8212e69d1f24ea13e',
    messagingSenderId: '198087606683',
    projectId: 'curso-flutter-cd410',
    storageBucket: 'curso-flutter-cd410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk41I9dm5vVSzi_vFVH9_xuBc24dzI1Fk',
    appId: '1:198087606683:ios:7bfe195b1ff4e7d14ea13e',
    messagingSenderId: '198087606683',
    projectId: 'curso-flutter-cd410',
    storageBucket: 'curso-flutter-cd410.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk41I9dm5vVSzi_vFVH9_xuBc24dzI1Fk',
    appId: '1:198087606683:ios:7bfe195b1ff4e7d14ea13e',
    messagingSenderId: '198087606683',
    projectId: 'curso-flutter-cd410',
    storageBucket: 'curso-flutter-cd410.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByrYl-HEWdr9k0bzZ3bc8_yinF4ETDYfo',
    appId: '1:198087606683:web:8e8bd0f79d78f2964ea13e',
    messagingSenderId: '198087606683',
    projectId: 'curso-flutter-cd410',
    authDomain: 'curso-flutter-cd410.firebaseapp.com',
    storageBucket: 'curso-flutter-cd410.appspot.com',
  );
}
